ktor:
    application:
        modules:
            - com.cinema.ApplicationKt.module
    deployment:
        port: "$APP_PORT"

database:
    url: "$PG_URL"
    user: "$PG_USER"
    password: "$PG_PASS"
    pool: 5